### PR TITLE
Install software required for Composer patches to work.

### PR DESCRIPTION
**Pull request by jose-oliveira**

### CODE REVIEW

**Comment by mstenta** [comment]
I've been using this image for years with `cweagans/composer-patches` without an issue. Although maybe it depends on which image variant you're using?

@jose-oliveira which image variant are you using? Maybe it extends from an image that doesn't have `patch` already, but others do?

**Comment by jose-oliveira** [comment]
Thanks @mstenta ! I made some changes to only add it on Alpine for Drupal versions greater than 7.

**Comment by jose-oliveira** [comment]
@tianon You need to `composer require cweagans/composer-patches` and declare at least one patch to your project to see an error. Although this isn't part of Drupal core Composer dependencies it's a very common use case.

**Comment by andypost** [comment]
The GNU patch utility is required for all core versions not only 8+, otherwise you will not be able to patch binary files at least

**Comment by chrisguindon** [comment]
We experienced this issue this week and found a workaround that worked for us. Not sure if this is the same problem but I will share since it seems similar enough.

We created a new Dockerfile that pulls `FROM drupal:9.5.10-apache` and we needed tp delete the ./web/core folder before running `composer install  --prefer-dist`:

 ```dockerfile
RUN  rm -r ./web/core; \
  composer install --prefer-dist; \
```
So far, this is the only way we found that allowed us to patch core via docker.

**Comment by mstenta** [comment]
Yes it's worth noting that you can always fix this by creating your own `Dockerfile` that inherits from this one, and installing `patch` in your image.

So the question is: does the Alpine version of this base image need to have `patch` included by default, considering it is only needed if you are using the `cweagans/composer-patches` package in your own `composer.json`? Not every user of this image needs that, although to be fair: a) a lot of custom Drupal sites do require patching core/contrib, b) `patch` is small and the other variants of this image already include it.

My sense is the maintainers of this image intentionally keep it very minimal, with the expectation that you will extend it with your own `Dockerfile` if you need do anything beyond what Drupal core by itself needs. I assume that was the spirit of @tianon's question:

> Is this something that's already supported by Drupal / Composer as they exist in the image today, or optional behavior that requires something additional to be installed/configured to enable?

Patching core/contrib is optional behavior not required by Drupal core itself. But it is often needed in Drupal-based projects.

**Comment by tianon** [comment]
Indeed - the intent is that it's relatively easy for users to install `patch` if they need it (for this completely optional extra workflow), but it's very hard for them to actually remove it in a functional way if we include it by default. :bow: :heart:

**Pull request closed without merging**
