### PR TITLE
Install Drush.

### PR DESCRIPTION
**Pull request by mstenta**
This pull request installs Drush via the recommended method.

It satisfies this issue: https://github.com/docker-library/drupal/issues/60

### CODE REVIEW

**Comment by aschonbe** [comment]
Thank you for your contribution; I personally appreciate it, but I would vote against merging this.

The point of this repository is to offer a [bare minimum core implementation](https://github.com/docker-library/official-images#review-guidelines) of Drupal, that subsequent child images can use as a parent and it should be as "light" as possible. It's not this image's "job" to dictate what tools the end user should use or needs to use nor is it meant to offer a full suite of products. Drush can be easily be installed in a child image of this OR be run as a separate container with Docker-Compose or whatever tool the user might want. IMHO, there are plenty of other tools and modules that are just as useful as Drush, but that doesn't necessarily mean we should pile them on.

Obviously there's a lot of subjectivity and an inherent debate on deciding what the minimum is; we can satisfy a wider array of opinions by keeping the base image as light as possible. I would personally not be against creating a separate array of tags that would include Drush (i.e. 8.x.x-apache-with-drush), but I understand that would increase the tag array's complexity.

Lastly, does the proposed Drupal 8 implementation actually work? I haven't had any success running Drush in this exact manner (with Drupal connected to a MariaDB/MySQL server) without first installing `mysql-client` on the container. Please confirm if anyone has tested it.

**Comment by mstenta** [comment]
General consensus is that Drush should not be included in this image by default. I now agree with that.

**Comment by wavesailor** [comment]
As I'm new to Docker, I'd like to know how I install and use Drush within a Drupal container?

**Comment by theodorosploumis** [comment]
@wavesailor Drush is a tool. You can install this on the Dockerfile or find out some other options. See here: for examples: [How to use docker with drupal and drush?](https://stackoverflow.com/q/35743801/1365264)

**Pull request closed without merging**
